from batchlib import *
NF=RAW(None,[],[])
raw={
"DMR":RAW(P("DMR","Sports & Outdoors","Bike Grips",6.88,"",False,"",0.051,-0.165,-0.201,62,4.52,41,2575,8884.73,95787.59),[],[]),
"Mermaid Soul":NF,
"Miss Hannah's Gourmet Popcorn":RAW(P("Miss Hannah's Gourmet Popcorn","Grocery & Gourmet Food","Popped Popcorn",0.85,"",False,"",0,-0.019,10.059,34.99,4.13,13,44,5948.3,73772.43),
 S(("Miss Hannah's Gourmet Popcorn Co.",100)),
 T(("Miss Hannah's Gourmet Sea Salted Brulee Popcorn, 16oz (3 Pack)","B0F47LZJ3Q",1679.52),("Miss Hannah's Gourmet Kettle Corn, 16oz (3 Pack)","B0F47DQBFC",1434.59),("Miss Hannah's Gourmet Popcorn Starter Pack, 3 Pack Gift Set","B0F2G66HNY",1434.59),("Miss Hannah's Gourmet Popcorn Party Pack, 3 Pack Gift Set","B0F2GKGPKR",629.82),("Miss Hannah's Gourmet Popcorn Classic Bundle, 3 Pack Gift Set","B0F2GN67YL",454.87))),
"Momentum":RAW(P("Momentum","Camera & Photo","Science Fiction Adventures",5.4,"Amazon.com",False,"",0.764,-0.165,-0.98,24.96,4.4,10,2430,470.44,1576.5),[],[]),
"Moose Haven Farm":RAW(P("Moose Haven Farm","Beauty & Personal Care","Face Moisturizers",1,"",False,"",0,0.167,None,25,5,1,6,275,1875),
 S(("Moose Haven Farm",100)),
 T(("Moose Haven Farm Balm Haven, Grass Fed Tallow and Manuka Honey Balm, 1 oz","B0FZ7KQMYZ",275))),
"The Mug Experience":NF,
"NORTY":RAW(P("NORTY","Clothing, Shoes & Jewelry","Women's Ankle Boots & Booties",1.35,"BCClothing",True,"https://www.amazon.com/stores/NORTY/page/D2AAE695-229E-4352-93F5-47177381A392",0,-0.341,-0.647,23.34,4.17,379,29495,29393.08,965220),
 S(("BCClothing",100)),
 T(("NORTY Men's Water Shoes, Quick-Dry Aqua Socks, Navy, Size 14","B01N8ZV3QW",588.75),("NORTY Men's Water Shoes, Quick-Dry Aqua Socks, Black, Size 14","B01MTMZCZG",567.6),("NORTY Men's Water Shoes, Quick-Dry Aqua Socks, Black, Size 17","B09WPBH457",476.52),("NORTY Men's Water Shoes, Quick-Dry Aqua Socks, Navy, Size 16","B0DV698JR4",474),("NORTY Men's Water Shoes, Quick-Dry Aqua Socks, Navy, Size 15","B01MTMZC2D",449.35))),
"magic Opener":RAW(P("magic Opener","Kitchen & Dining","Bottle Openers",1,"",True,"https://www.amazon.com/stores/magicopener/page/C1F7E4B3-6A6D-4C19-BB78-53480843C149",0,0.023,-0.486,27.49,4.35,2,3592,8667.02,121177.44),
 S(("magic Opener",100)),
 T(("Bottle Opener Combo, Water Bottle Opener, Soda & Plastic Caps, 16 Sizes","B018KFII4G",7317.56),("magic Opener EXTREME, Soda & Water Plastic Caps, Arthritis Helper","B009G5MDHI",1349.46))),
"Nest New York":RAW(P("Nest New York","Home & Kitchen","Reed Diffuser Sets",1.06,"",False,"",0.078,-0.324,0.246,52.05,4.41,233,19917,1428295.91,25546764.99),[],[]),
"PEARSON RANCH SINCE 1959":RAW(P("PEARSON RANCH SINCE 1959","Grocery & Gourmet Food","Jerky",0.76,"Tru Inertia",True,"https://www.amazon.com/stores/PearsonRanch/page/19EE25B0-E806-44C5-A4D1-4491ECDE0318",0,-0.109,-0.089,34.79,4.36,38,4910,46307.63,997434.96),
 S(("Tru Inertia",100)),
 T(("Pearson Ranch Meat Sticks Variety Pack, Elk, Bison, Venison, Wild Boar, 24 Count","B07DQVDHYR",8690.36),("Pearson Ranch Exotic Game Meat Summer Sausage Gift Set of 3","B07284DYDL",6228.22),("Pearson Ranch Grass Fed Elk Meat Sticks, 24 Count","B07DQSWG88",4783.08),("Pearson Ranch Meat Sticks Variety Pack, 12 Count","B07DQXRZVM",3014.96),("Pearson Ranch Wild Game Summer Sausage Gift Set, 5-Pack","B096L14XNP",2939.51))),
"PERRIN":RAW(P("PERRIN","Automotive","License Plate Frames",10.89,"",False,"",0,-0.165,-0.561,64.45,4.61,9,2115,4273.01,26019.38),[],[]),
"Planet Cotton":NF,
"Please Please Me":NF,
"Pocket Products":NF,
"Prairie Mountain":NF,
"RFSJ INC.":RAW(P("RFSJ INC.","Sports & Outdoors","Sports Fan Coffee Mugs",0.99,"",False,"",0,0.151,-0.007,31.07,4.65,340,5865,67752.19,1570488.9),
 S(("Sports Team Accessories",100)),
 T(("RFSJ INC. Notre Dame Fighting Irish Satin Finish Rock Glass Set of 2 14oz","B085JQ171N",1869.45),("Notre Dame Fighting Irish Sculpted Contoured Relief Mug 16 oz","B0C954JHKK",1439.52),("RFSJ INC. Utah Utes 2-Sided Satin Finish Rock Glass Set of 2 14oz","B0GMKF7865",577.83),("Northwestern Wildcats 2-Sided Satin Finish Rock Glass Set of 2 14oz","B0GMKC748F",509.85),("RFSJ INC. UCF Knights 2-Sided Satin Finish Rock Glass Set of 2 14oz","B0GMKVKT6R",509.85))),
"Ramatex":RAW(P("Ramatex","Home & Kitchen","Bed Blankets",1,"",False,"",0,None,None,69.99,5,1,7,139.98,0),
 S(("Jetienne",100)),
 T(("Ramatex Unisex Pine Cabin Melange Sherpa Reversible Blanket, 80X61","B07XTR8Q13",139.98))),
"REDNECK SUNSCREEN":RAW(P("REDNECK SUNSCREEN","Beauty & Personal Care","Sunscreens",1,"",False,"",0,1.128,1.215,13.49,4.7,2,94,1933.58,4732.5),
 S(("Redneck Sunscreen",100)),
 T(("Sport Sunscreen Spray SPF 50, Water & Sweat Resistant, 6 Oz","B096YGNXC5",1245.11),("Redneck Sunscreen SPF 50 Sport Lotion, Water Resistant, 6 Oz","B096YFT2C9",688.47))),
"Thunderbird Real Food Bars":RAW(P("Thunderbird Real Food Bars","Health & Household","Sports Nutrition Endurance & Energy Bars",1.36,"Thunderbird Real Food Bars",True,"https://www.amazon.com/stores/Thunderbird/page/BCB6C0F5-F126-4BD8-8DDA-FD99B628CBAC",0,-0.04,-0.303,23.63,4.2,42,1209,56029.53,529756.29),
 S(("Thunderbird Real Food Bars",99.696),("TheNewMall",0.265),("Amazon.com",0.025),("AmazingAHF",0.013),("USTradeEnt",0)),
 T(("Thunderbird Bars Variety Flavor Pack, 12 Count","B0BST4VFV9",7983.58),("Thunderbird Real Food Bars Variety Pack, 102 Ounce","B097CGVXGZ",4633.56),("Thunderbird Bars Hazelnut Coffee Maca, 12 Count","B08ZQBNVVJ",4226.49),("Thunderbird Cashew Fig Carrot Bars, 12 Pack","B08ZQ8K6KH",4086.54),("Thunderbird Bars Chocolate Almond Butter Sea Salt, 12 Count","B08ZQHBM3S",3167.04))),
"TipsyAuthen":RAW(P("TipsyAuthen","Electronics","Earbud & In-Ear Headphones",1,"",True,"https://www.amazon.com/stores/Tipsy-HeartheTruth/page/C29736B9-C811-4D8E-A471-877D0A90E144",0,0.13,None,126.85,4.53,13,430,151226.15,975859.79),
 S(("TipsyAudio",100)),
 T(("Tipsy M5 Ultra IEM, 5-Driver Hybrid","B0GLF1G6LH",29579.96),("TipsyAuthen Tipsy M3 Professional IEM (Green)","B0FGJ3B7PM",28487.7),("TipsyAuthen Tipsy M3 Professional IEM (Black & White)","B0FGJ4V6W1",27266.56),("Tipsy M1 IEM, Bamboo Fiber Diaphragm (Blue)","B0FGCCKQ5B",21583),("TipsyAuthen Tipsy M3 Professional IEM (Red)","B0FGJ7MSFD",16834.11))),
"Topline":RAW(P("Topline","Tools & Home Improvement","Tool Sets",0.97,"TOPLINE TOOLS",True,"https://www.amazon.com/stores/TOPLINE/page/AE903738-B192-42FF-BF6A-E239BC929379",0,-0.22,-0.22,27.2,4.52,39,11160,93808.95,1316394.73),
 S(("TOPLINE TOOLS",85.241),("Topline retail Solutions",14.759),("TheNewMall",0),("ToplineMachinery",0)),
 T(("TOPLINE 467-Piece Household Home Tool Kit with Bag","B08XPBR9JD",30116.43),("TOPLINE 4-piece Groove Joint Pliers Set","B08B656J9M",8035.29),("Topline Fire Starters 500-Pack Bulk Supply","B09RQWXQ97",7152.54),("Topline 14-Piece Allen Wrench Set","B08Y56175P",6918.66),("Topline 100 Fire Starters in Storage Tube","B09RQWN4KC",6684.96))),
"Tortuga Moon":NF,
"Travel Depot":RAW(P("Travel Depot","Automotive","Automotive Seat Back Organizers",1,"Cyberguys!",True,"https://www.amazon.com/stores/TRAVELDEPOT/page/1610419F-768E-4EEA-B188-DB5CB1C68F89",0,0.032,2.79,26.87,4.37,18,678,47422.64,302333.79),[],[]),
"TrendSetterTees":NF,
}
LV="Saw you're exhibiting at the Las Vegas Souvenir & Resort Gift Show next week."
H="Hi {{first_name}},"
CO="We manage Amazon for brands end to end, including strategy, content, advertising, inventory and operations."
PROOF="We recently helped a brand go from no Amazon presence to a $1M+ annual run rate within six months."
END="We manage the channel end to end."
ASK_NF="Is Amazon something you're looking at more seriously?"
KL="Las Vegas Souvenir & Resort Gift Show 2026|"
def nf(row,key,q,angle,points,subject,body,qa,opener=LV,ask=ASK_NF,conf="not found"):
    return E(row,key,q,angle,points,subject,f"""{H}\n\n{opener}\n\n{body}\n\n{PROOF} {END}\n\n{ask}\n\nYoni""",conf=conf,qa=qa)
def ok(row,key,q,angle,points,subject,body,ask,qa,brand_sellers=None,conf=None):
    return E(row,key,q,angle,points,subject,f"""{H}\n\n{LV}\n\n{body}\n\n{CO}\n\n{ask}\n\nYoni""",conf=conf,brand_sellers=brand_sellers,qa=qa)
ASK_DROP="Open to a 20 minute look at where the drop is coming from?"
ASK_Q4="Would it make sense to have a quick conversation before Q4?"
emails=[
nf(1291,KL+"DMR Creative","DMR","Wrong match; 'DMR' on Amazon is a bike parts brand; second attempt 'DMR Creative' empty; industry-level email","'DMR' record (~$9k/mo, bike grips) unrelated; 'DMR Creative' returned empty; sheet listing seller unknown","DMR Creative on Amazon",
"From what we can see, DMR Creative doesn't have a brand presence on Amazon, and searches for the name land on an unrelated bike parts brand. For a gift-show exhibitor, Amazon is where people go to look after they've seen a product on a trip, and right now nothing under the name catches that.",
["wrong match: 'DMR' record is a bike parts brand; 'DMR Creative' returned empty; sheet seller unknown","industry-level email"],conf="wrong match"),
nf(1386,KL+"Mermaid Soul","Mermaid Soul","Not found; sheet listing is a book; industry-level email","No brand record on two attempts; sheet listing (ISBN) is a book, not a product line","Mermaid Soul on Amazon",
"From what we can see, Mermaid Soul doesn't have a brand presence on Amazon, and the only listing tied to the name is a book. Coastal gift lines get searched on Amazon by people who saw a piece on vacation, and a storefront with a few well-built listings is a small way to catch that before the holidays.",
["no brand record on two attempts; sheet listing is a book; industry-level email"]),
ok(1389,KL+"Miss Hannah's Gourmet Popcorn","Miss Hannah's Gourmet Popcorn","Small, new footprint sold brand direct; thin reviews on gift bundles ahead of Q4","~$6k/mo; 13 listings; 44 reviews; 4.1 rating; 100% brand seller; three-packs and gift sets lead; run rate up sharply on the year from a near-zero base","Miss Hannah's popcorn on Amazon",
"Looking at your listings, Miss Hannah's is doing about $6k a month on Amazon through your own account, with the three-packs and gift sets carrying it and the listings still new, at under 50 reviews across the catalog. Gourmet popcorn gift sets are a real Q4 search on Amazon, and the gap right now is reviews and advertising behind the gift bundles.",
ASK_Q4,["sheet Brand (Seller Central) confirmed","fresh data shows no storefront flag though sheet found a brand store"]),
nf(1391,KL+"Momentum Comfort Gear","Momentum","Wrong match; 'Momentum' record is unrelated media sold by Amazon; second attempt 'Momentum Comfort Gear' empty; industry-level email","'Momentum' record is an unrelated Camera & Photo / media brand; 'Momentum Comfort Gear' returned empty; sheet listing sold by Amazon.com unverified","Momentum Comfort Gear on Amazon",
"From what we can see, Momentum Comfort Gear doesn't have a brand presence on Amazon, and searches for the name land on unrelated listings. Comfort and travel gear is a big gift category on Amazon, and a storefront with a few well-built listings is a small way to catch people who saw the line at a resort shop.",
["wrong match: 'Momentum' record unrelated; 'Momentum Comfort Gear' returned empty; sheet Amazon (Vendor) not confirmed","industry-level email"],conf="wrong match"),
ok(1395,KL+"Moose Haven Farm","Moose Haven Farm","Tiny footprint sold brand direct; one listing, strong early rating","~$300/mo; 1 listing (tallow and manuka balm); 6 reviews; 5.0 rating; 100% brand seller","Moose Haven Farm on Amazon",
"Looking at your listings, Moose Haven Farm is on Amazon with one tallow balm listing doing a few hundred dollars a month through your own account. Six reviews and a 5.0 rating is a good sign on the product. The gap is one listing with nothing behind it, so from what we can see most of the search for tallow balm goes to other brands.",
ASK_NF,["sheet Brand (Seller Central) confirmed"]),
nf(1397,KL+"Mug Experience","The Mug Experience","Not found; record exists with zero products; sheet listing sold by Hour Loop; industry-level email","Empty brand record on 'The Mug Experience' and 'Mug Experience'; sheet listing sold by reseller Hour Loop","The Mug Experience on Amazon",
"From what we can see, The Mug Experience doesn't have a brand presence on Amazon, and the one listing tied to the name is sold by a reseller rather than the brand. Mugs are one of the biggest souvenir searches on Amazon, and a storefront with a few well-built listings is a small way to catch people who saw the line on a trip.",
["empty brand record on two attempts; sheet third-party (Hour Loop); industry-level email"]),
ok(1406,KL+"Norty Footwear & Clothing","NORTY","Revenue well below what a 380-listing, 30k-review catalog suggests; down about two-thirds on the year; whole channel through one account (BCClothing)","~$29k/mo; 379 listings; 29,495 reviews; 4.17 rating; BCClothing 100%; MoM -34%; 12-month MoM -65%; storefront present","Norty on Amazon",
"Looking at your listings, Norty is doing about $29k a month on Amazon across roughly 380 listings and close to 30,000 reviews, down about two-thirds on the year, and all of it runs through an account called BCClothing rather than a Norty account. A catalog with that many reviews should do far more than $29k, so the drop is likely ranking and listing health, not demand.",
ASK_DROP,["sheet third-party (BCClothing) confirmed; BCClothing may be Norty's own account, verify"]),
ok(1415,KL+"Openers Plus","magic Opener","Down about half on the year on two listings with 3,600 reviews; sold brand direct","~$9k/mo; 2 listings; 3,592 reviews; 4.35 rating; 100% brand seller; 12-month MoM -49%; storefront present","Magic Opener on Amazon",
"Looking at your listings, Magic Opener is doing about $9k a month on Amazon through your own account, on two listings with about 3,600 reviews between them, but the run rate is down roughly half on the year. A product with that many reviews doesn't lose half its sales because people stopped wanting it. It's usually ranking, pricing or a competitor's ads, and it's fixable.",
ASK_DROP,["sheet Brand (Seller Central) confirmed; exhibitor Openers Plus, brand on Amazon is magic Opener"]),
nf(1420,KL+"Pacific North Nest Designs","NEST New York","Wrong match; sheet mapped to NEST New York (home fragrance, ~$1.4M/mo); second attempt 'Pacific North Nest' empty; industry-level email","'Nest New York' record is an unrelated home fragrance brand; 'Pacific North Nest' returned empty","Pacific North Nest on Amazon",
"From what we can see, Pacific North Nest Designs doesn't have a brand presence on Amazon, and searches for the name land on an unrelated home fragrance brand. Pacific Northwest themed gifts get searched on Amazon by people who bought a piece on a trip, and a storefront with a few well-built listings is a small way to catch that before the holidays.",
["wrong match: sheet mapped exhibitor to NEST New York (home fragrance), unrelated; 'Pacific North Nest' returned empty","industry-level email"],conf="wrong match"),
ok(1426,KL+"Pearson Ranch Elk & Bison Jerky","PEARSON RANCH SINCE 1959","Whole channel through one account (Tru Inertia); run rate down about 10% on the year heading into gift season","~$46k/mo; 38 listings; 4,910 reviews; 4.36 rating; Tru Inertia 100%; MoM -11%; 12-month MoM -9%; storefront present; variety packs and gift sets lead","Pearson Ranch on Amazon",
"Looking at your listings, Pearson Ranch is doing about $46k a month on Amazon, with the exotic meat stick variety packs and gift sets carrying it, and all of it runs through an account called Tru Inertia rather than a Pearson Ranch account. If that's your partner, fine. Either way the run rate is down about 10% on the year heading into the gift season, which is when jerky gift sets do their best.",
ASK_Q4,["sheet third-party (Tru Inertia) confirmed; Tru Inertia may be an affiliated account, verify"]),
nf(1427,KL+"Perrin Sportswear","Perrin","Wrong match; 'PERRIN' on Amazon is an automotive parts brand; sheet listing is a print-on-demand shirt; second attempt 'Perrin Sportswear' empty; industry-level email","'PERRIN' record (~$4k/mo, license plate frames) unrelated; 'Perrin Sportswear' returned empty; sheet listing is a novelty shirt sold by Amazon","Perrin Sportswear on Amazon",
"From what we can see, Perrin Sportswear doesn't have a brand presence on Amazon, and the only listings tied to the name are an unrelated auto parts brand and a novelty shirt. Souvenir apparel gets searched by name on Amazon by people who bought a piece on a trip, and a storefront with a few well-built listings is a small way to catch that.",
["wrong match: 'PERRIN' record is automotive; sheet listing is a print-on-demand shirt sold by Amazon","industry-level email"],conf="wrong match"),
nf(1432,KL+"Planet Cotton/ Blue Moon","Planet Cotton","Not found; sheet mapped to Carter's Little Planet (unrelated); 'Blue Moon' returned an unrelated music record; industry-level email","'Planet Cotton' empty; 'Blue Moon' record is unrelated (Books, Classic R&B); sheet mapping to little planet by carter's is wrong","Planet Cotton on Amazon",
"From what we can see, Planet Cotton doesn't have a brand presence on Amazon, and searches for the name land on unrelated listings. Resort apparel gets searched by name on Amazon by people who bought a piece on a trip, and a storefront with a few well-built listings is a small way to catch that before the holidays.",
["no brand record on two attempts; sheet mapped to little planet by carter's, unrelated; 'Blue Moon' returned unrelated music record","industry-level email"]),
nf(1433,KL+"Please Please Me","Please Please Me","Not found; sheet listing seller unknown; industry-level email","No brand record on two attempts; sheet listing seller not shown","Please Please Me on Amazon",
"From what we can see, Please Please Me doesn't have a brand presence on Amazon, and the one listing tied to the name isn't sold by the brand. Gift lines with a name people remember get searched on Amazon after a trip, and a storefront with a few well-built listings is a small way to catch that before the holidays.",
["no brand record on two attempts; sheet listing seller unknown; industry-level email"]),
nf(1434,KL+"Pocket Products, LLC","Pocket Products","Not found; sheet storefront (Pocket AI) is an unrelated electronics brand; 'Pocket AI' also returned empty; industry-level email","'Pocket Products' and 'Pocket AI' both empty; sheet mapping to Pocket AI storefront looks unrelated","Pocket Products on Amazon",
"From what we can see, Pocket Products doesn't have a brand presence on Amazon, and the storefront tied to the name belongs to an unrelated electronics brand. Souvenir and gift lines get searched on Amazon by people who saw a piece on a trip, and a storefront with a few well-built listings is a small way to catch that before the holidays.",
["no brand record on two attempts; sheet mapped to Pocket AI storefront, likely unrelated","industry-level email"]),
nf(1436,KL+"Prairie Mountain","Prairie Mountain","Not found; sheet listing is a print-on-demand shirt sold by Amazon; industry-level email","No brand record on two attempts; sheet listing is a novelty shirt","Prairie Mountain on Amazon",
"From what we can see, Prairie Mountain doesn't have a brand presence on Amazon, and the only listing tied to the name is an unrelated novelty shirt. Destination apparel gets searched by name on Amazon by people who bought a piece on a trip, and a storefront with a few well-built listings is a small way to catch that before the holidays.",
["no brand record on two attempts; sheet listing is a print-on-demand shirt; industry-level email"]),
ok(1441,KL+"R.F.S.J. Inc.","RFSJ INC.","Whole channel through one account (Sports Team Accessories); flat on the year across a 340-listing licensed catalog heading into Q4","~$68k/mo; 340 listings; 5,865 reviews; 4.65 rating; Sports Team Accessories 100%; MoM +15%; 12-month MoM flat; no storefront flag in fresh data","RFSJ collegiate glassware on Amazon",
"Looking at your listings, RFSJ is doing about $68k a month on Amazon across roughly 340 listings of licensed collegiate glassware and mugs, flat on the year, and all of it runs through an account called Sports Team Accessories rather than an RFSJ account. If that's your own store, fine. Either way, flat on a catalog that size heading into Q4 means most of it isn't getting advertising or content attention.",
ASK_Q4,["sheet third-party (Sports Team Accessories) confirmed; may be RFSJ's own account, verify","fresh data shows no storefront flag though sheet found a brand store"]),
ok(1446,KL+"Ramatex International","Ramatex","Almost no footprint for an established blanket maker; one listing sold by a reseller","~$140/mo; 1 listing (sherpa blanket); 7 reviews; 5.0 rating; Jetienne 100%; sheet named SPLG Products as seller","Ramatex blankets on Amazon",
"Looking at your listings, Ramatex is barely on Amazon, with one sherpa blanket listing doing next to nothing and sold by a reseller rather than a Ramatex account. Blankets and throws are one of the biggest gift searches on Amazon in Q4, and a brand with a full line has almost nothing built there to catch it.",
ASK_NF,["sheet third-party (SPLG Products); fresh data shows Jetienne as the seller","close match: exhibitor Ramatex International, record Ramatex"],conf="close"),
ok(1447,KL+"Redneck Sunscreen LLC","REDNECK SUNSCREEN","Small but growing fast, sold brand direct; two listings, thin reviews, no storefront flag","~$2k/mo; 2 listings; 94 reviews; 4.7 rating; 100% brand seller; MoM +113%; 12-month MoM +122%","Redneck Sunscreen on Amazon",
"Looking at your listings, Redneck Sunscreen is doing about $2k a month on Amazon through your own account on two listings, with a 4.7 rating and the run rate up sharply on the year. That's a good sign on product. Sunscreen is a search-driven category on Amazon, and two listings with thin reviews can only catch so much of it, especially with a name people remember.",
"Would it make sense to have a quick conversation about growing the channel?",["sheet Brand (Seller Central) confirmed","fresh data shows no storefront flag though sheet found a brand store"]),
ok(1513,KL+"Thunderbird Manufacturing","Thunderbird Real Food Bars","Down about 30% on the year on a brand-direct catalog; rating at 4.2 capping conversion","~$56k/mo; 42 listings; 1,209 reviews; 4.2 rating; brand seller 99.7%; MoM -4%; 12-month MoM -30%; storefront present; variety packs lead","Thunderbird bars on Amazon",
"Looking at your listings, Thunderbird is doing about $56k a month on Amazon through your own account, with the variety packs and the hazelnut coffee bar carrying it, but the run rate is down about 30% on the year. On a 40-listing catalog with a 4.2 rating, that usually traces to a few listings losing rank and a rating that's capping conversion, and both are fixable.",
ASK_DROP,["sheet Brand (Seller Central) confirmed"]),
ok(1515,KL+"Tipsy","TipsyAuthen","Strong and growing, sold brand direct; revenue high relative to a thin review base","~$150k/mo; 13 listings; 430 reviews; 4.53 rating; TipsyAudio 100%; MoM +13%; storefront present; M3 and M5 in-ear monitors lead","Tipsy on Amazon",
"Looking at your listings, Tipsy is doing about $150k a month on Amazon through your own account across 13 in-ear monitor listings, and growing. What stands out is only about 430 reviews behind that much revenue, which means the listings are converting on product and price rather than social proof, and one bad month of reviews can move rank fast.",
"Open to a 20 minute look at the next stretch of growth?",["verify identity: exhibitor 'Tipsy' at a gift show; Amazon record is the Tipsy audio brand (TipsyAuthen / TipsyAudio) per sheet store URL","sheet Brand (Seller Central) confirmed"],brand_sellers=["TipsyAudio"],conf="close"),
ok(1517,KL+"Topline Products, Inc.","Topline","Down about 20% on the year on a brand-direct catalog with 11,000 reviews","~$94k/mo; 39 listings; 11,160 reviews; 4.52 rating; TOPLINE TOOLS 85%, Topline retail Solutions 15%; MoM -22%; 12-month MoM -22%; storefront present; household tool kit leads","Topline tools on Amazon",
"Looking at your listings, Topline is doing about $94k a month on Amazon, mostly through the Topline Tools account, with the big household tool kit carrying about a third of it and the run rate down about 20% on the year. On a catalog with 11,000 reviews and a 4.5 rating, a drop like that is usually ranking or advertising on the top few listings rather than demand, and it's fixable.",
ASK_DROP,["verify identity: exhibitor Topline Products, Inc.; Amazon record is TOPLINE TOOLS per sheet store URL","sheet Brand (Seller Central) confirmed; Topline retail Solutions (15%) treated as affiliated, verify"],brand_sellers=["TOPLINE TOOLS","Topline retail Solutions"],conf="close"),
nf(1519,KL+"Tortuga Moon - Cole Apparel","Tortuga Moon","Not found; record exists with zero products; sheet mapped to Tortuga Rum Cake storefront (unrelated); 'Cole Apparel' empty; industry-level email","Empty brand record on 'Tortuga Moon'; 'Cole Apparel' empty; sheet mapping to TORTUGA rum cake store is wrong","Tortuga Moon on Amazon",
"From what we can see, Tortuga Moon doesn't have a brand presence on Amazon, and the storefront tied to the name belongs to an unrelated rum cake brand. Resort apparel gets searched by name on Amazon by people who bought a piece on a trip, and a storefront with a few well-built listings is a small way to catch that before the holidays.",
["empty brand record on two attempts; sheet mapped to Tortuga Rum Cake storefront, unrelated","industry-level email"]),
nf(1522,KL+"TRAVEL SIZE DEPOT","Travel Depot","Wrong match; sheet mapped to Travel Depot (car seat organizers, ~$47k/mo); 'Travel Size Depot' empty; industry-level email","'Travel Depot' record is an unrelated automotive organizer brand; 'Travel Size Depot' returned empty","Travel Size Depot on Amazon",
"From what we can see, Travel Size Depot doesn't have a brand presence on Amazon, and the storefront tied to the name belongs to an unrelated car organizer brand. Travel size toiletries are one of the most searched convenience categories on Amazon, and a storefront with a few well-built bundles is a small way to catch that.",
["wrong match: sheet mapped exhibitor to Travel Depot (automotive), unrelated; 'Travel Size Depot' returned empty","industry-level email"],conf="wrong match"),
nf(1524,KL+"TrendSetterTees, LLC.","TrendSetterTees","Not found; sheet listing is a print-on-demand shirt sold by Amazon; industry-level email","No brand record on two attempts; sheet listing is a novelty shirt","TrendSetterTees on Amazon",
"From what we can see, TrendSetterTees doesn't have a brand presence on Amazon, and the only listing tied to the name is an unrelated novelty shirt. Souvenir tees get searched by name on Amazon by people who bought one on a trip, and a storefront with a few well-built listings is a small way to catch that before the holidays.",
["no brand record on two attempts; sheet listing is a print-on-demand shirt; industry-level email"]),
]
run(raw,emails)
